run:
  tests: true
  timeout: 5m
  concurrency: 4

linters:
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll TODO: enable
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - nolintlint
    - asciicheck
    - exportloopref
    - gofumpt

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
  gofumpt:
    lang-version: "1.22"
