// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type MissedBlock struct {
	ID          int64
	Height      int64
	ValidatorID int64
	Missed      int64
}

type Validator struct {
	ID               int64
	OperatorAddress  string
	Pubkey           string
	ValidatorAddress string
	Moniker          string
	Indentity        string
}
